#! /bin/sh

#xsetroot -cursor_name left_ptr    

#sxhkd &

#xfce4-power-manager &

#nitrogen --restore &

#compton -b &

#windscribe connect &

#run variety &

$HOME/.config/polybar/launch.sh

$HOME/.config/bspwm/autostart.sh &

   ${BG}

bspc monitor DVI-I-1 -d 1 2 3
bspc monitor HDMI-0 -d 4 5 6

bspc config initial_polarity first_child focus

bspc config border_width        1 
bspc config window_gap          80
bspc config focused_border_color \#665c54
bspc config active_border_color \#121212

bspc config top_padding 18
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc config pointer_modifier mod1
bspc config click_to_focus false
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Pavucontrol desktop='^' state=floating follow=on
bspc rule -a Nitrogen desktop='^' state=floating 
bspc rule -a Lxappearance desktop='^' state=floating follow=on
bspc rule -a Nvidia-settings desktop='^' state=floating follow=on
bspc rule -a GParted desktop='^' state=floating follow=on
bspc rule -a Firefox desktop='^'
bspc rule -a MPlayer state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Oblogout state=floating
bspc rule -a Bleachbit state=floating


#! /bin/sh
# ~/.config/bspwm/bspwmrc

#...

bspc config external_rules_command ~/.config/bspwm/external_rules.sh
